adds must_select_whole_seat_block to AvailabilityMeta
ingresso-group/pyticketswitch pull request #101
Opened 2020-10-23 12:28 UTC by stevgouws

Does what it says on the tin: adds `must_select_whole_seat_block` to the AvailabilityMeta class.

2020-10-23 12:50 UTC, cakemanny approved these changes
Can't fault this :)

2020-10-23 12:53 UTC, cakemanny requested changes

2020-10-23 12:53 UTC, cakemanny commented on CHANGELOG.md
> +## [2.8.5] - 2018-05-29
Actually this!

2020-10-23 12:59 UTC, cakemanny requested changes
Actually I didn't review this very well at all

You also want to add it to the `__init__` method and the the class documentation

also there is a test in `tests/test_client.py` as well

```
~/src/pyticketswitch (master) % ag contiguous_seat_selection_only
tests/test_availability.py
107:        "contiguous_seat_selection_only": True,
129:        assert meta.contiguous_seat_selection_only is True

tests/test_client.py
1045:            'contiguous_seat_selection_only': True,
1064:        assert meta.contiguous_seat_selection_only is True

docs/users/advanced.rst
380:    >>> meta.contiguous_seat_selection_only
386:When :class:`contiguous_seat_selection_only
387:<pyticketswitch.availability.AvailabilityMeta.contiguous_seat_selection_only>`

pyticketswitch/availability.py
11:        contiguous_seat_selection_only (bool): indicates that the backend
36:    def __init__(self, contiguous_seat_selection_only=True, currency=None,
40:        self.contiguous_seat_selection_only = contiguous_seat_selection_only
68:        inst.contiguous_seat_selection_only = data.get('contiguous_seat_selection_only', True)
```
can leave the advanced.rst for later I think

2020-10-23 13:03 UTC, cakemanny commented
and don't worry about the ci build error for now. looks like that's never been set up
can come back to that

2020-10-23 14:00 UTC, stevgouws commented on CHANGELOG.md
> +## [2.8.5] - 2018-05-29
🤦 jeez, pre-lunch brain. Thanks!

2020-10-23 14:31 UTC, stevgouws commented
> Actually I didn't review this very well at all
> 
> You also want to add it to the `__init__` method and the the class documentation
> 
> also there is a test in `tests/test_client.py` as well
> 
> ```
> ~/src/pyticketswitch (master) % ag contiguous_seat_selection_only
> tests/test_availability.py
> 107:        "contiguous_seat_selection_only": True,
> 129:        assert meta.contiguous_seat_selection_only is True
> 
> tests/test_client.py
> 1045:            'contiguous_seat_selection_only': True,
> 1064:        assert meta.contiguous_seat_selection_only is True
> 
> docs/users/advanced.rst
> 380:    >>> meta.contiguous_seat_selection_only
> 386:When :class:`contiguous_seat_selection_only
> 387:<pyticketswitch.availability.AvailabilityMeta.contiguous_seat_selection_only>`
> 
> pyticketswitch/availability.py
> 11:        contiguous_seat_selection_only (bool): indicates that the backend
> 36:    def __init__(self, contiguous_seat_selection_only=True, currency=None,
> 40:        self.contiguous_seat_selection_only = contiguous_seat_selection_only
> 68:        inst.contiguous_seat_selection_only = data.get('contiguous_seat_selection_only', True)
> ```
> 
> can leave the advanced.rst for later I think

Updated 👉  https://github.com/ingresso-group/pyticketswitch/commit/a50a64fb3b90d5b2598daec1284a334031674ae9

2020-10-23 14:52 UTC, cakemanny approved these changes

2020-10-27 13:12 UTC, merged

2020-10-27 13:16 UTC, cakemanny commented
I pulled Steven's branch and ran the tests and made sure they passed
(in case anyone is reading this)