Added seat_apple_wallet_urls and seat_apple_wallet_urls to Seat
ingresso-group/pyticketswitch pull request #105
Opened 2022-01-20 02:11 UTC by charklewis

2022-01-21 09:30 UTC, ASamarin04 approved these changes
Looks good!

2022-01-21 10:25 UTC, cakemanny requested changes
Some code one has to write to use these would look like

```python
if seat.seat_apple_wallet_urls is not None:
    apple_wallet_url = seat.seat_apple_wallet_urls.get("apple_wallet_gen_url")
```
I think this is inconsistent with the design of `pyticketswitch`. I think it would be more consistent if `seat_apple_wallet_urls` was an object and the usage looked like :
```python
if seat.seat_apple_wallet_urls is not None:
    apple_wallet_url = seat.seat_apple_wallet_urls.apple_wallet_gen_url
```

2022-01-24 03:51 UTC, charklewis commented on CHANGELOG.md
> +
ah yup, thanks dan! I have updated these https://github.com/ingresso-group/pyticketswitch/pull/105/commits/1626632c75125c1de552611bd56e1ee58c5e71bf

2022-01-24 04:35 UTC, charklewis commented on tests/test_seat.py
> +            }
Ah thank you again Dan! After some exploring I noticed that these tests were never actually getting run. I have fixed this now and also updated the value for the wallets.

2022-01-24 04:36 UTC, charklewis commented
@ASamarin04 and @cakemanny I have updated the code based your feedback Dan. Let me know what you think. I wasn't able to test it against my local instance of my white label, so unsure 100% if it will work.

2022-01-24 05:01 UTC, charklewis commented
I managed to test it locally by using `pip install -e /Users/charleslewis/Code/pyticketswitch`. Not sure if there is a better way but this seemed to work for me.

2022-01-24 05:04 UTC, charklewis commented
This is the PR (https://github.com/ingresso-group/white-label/pull/3698) for the white label to consume this change. Note it is breaking as this version of pyticketswitch isn't deployed yet.

2022-01-24 11:19 UTC, cakemanny approved these changes
LGTM! :)

2022-01-24 11:27 UTC, merged