adding tax values to be expected in cost ranges
ingresso-group/pyticketswitch pull request #106
Opened 2022-01-26 14:35 UTC by joegrimeringresso

This is predicting changes in core, so won't be any good yet

needed for: https://accesso.atlassian.net/browse/DSTBACK-871

2022-01-26 14:53 UTC, joegrimeringresso commented
After some conversation with Pete, it turns out this is not what he expected. He thought groupon called the availability.v1 endpoint, when really it's calling the events.v1 endpoint - thus making adding these values a lot harder.

Meanwhile, I'm going to fix these tests

2022-03-22 10:55 UTC, cakemanny commented
You could include a step to upload coverage for this to codecov as well...

We already have a codecov badge on the readme, and codecov is free for public repos

2022-03-22 10:55 UTC, cakemanny commented
You could include a step to upload coverage for this to codecov as well...

We already have a codecov badge on the readme, and codecov is free for public repos

2022-05-05 10:45 UTC, cakemanny commented on pyticketswitch/client.py
> +            ead8fba84b12e7496c65272a07de47d553aa0ca0/requests/api.py#L57-L58
not sure if I'm supposed to be commenting on this yet, but I think this url might have snapped a bit :D

2022-05-05 10:52 UTC, cakemanny commented on pyticketswitch/client.py
> +                <pyticketswitch.client.Client.add_optional_kwargs>`
did you manage to build the docs and check whether breaking a line in between the backticks doesn't break them?

2022-05-05 11:49 UTC, joegrimeringresso commented on pyticketswitch/client.py
> +                <pyticketswitch.client.Client.add_optional_kwargs>`
you're right. This generates errors in the "make docs" command

2022-05-05 11:55 UTC, joegrimeringresso commented on pyticketswitch/client.py
> +            ead8fba84b12e7496c65272a07de47d553aa0ca0/requests/api.py#L57-L58
Yeah... I need to fix that

_I didn't realise you were still subscribed. You may want to unsubscribe_

2022-05-05 11:58 UTC, joegrimeringresso commented
THere seems to be a bug in `flake`. my doc lines are coming under `E501` line too long instead of `W505` doc line too long (which I've increased to 137

2022-05-05 13:40 UTC, joegrimeringresso commented
> THere seems to be a bug in `flake`. my doc lines are coming under `E501` line too long instead of `W505` doc line too long (which I've increased to 137

This was solved by being more careful with how I break the lines. The url one is no longer showing up

2022-05-05 13:45 UTC, joegrimeringresso commented
disabling netlify webhook

2022-05-05 13:48 UTC, joegrimeringresso commented
disabling netlify and travis webhooks

2022-05-11 13:32 UTC, cakemanny commented on README.md
> +- Issue Tracker: https://github.com/ingresso-group/pyticketswitch/issues (But Jira is now a thing)
This is a public repo. I wouldn't ask users of our library to raise issues via our private Jira instance ... I don't think it's a great CX.

2022-05-11 13:40 UTC, joegrimeringresso commented on README.md
> +- Issue Tracker: https://github.com/ingresso-group/pyticketswitch/issues (But Jira is now a thing)
oops. removed

2022-05-11 14:56 UTC, cakemanny requested changes
Hey I think there's still a few problems here

2022-05-11 14:56 UTC, cakemanny commented on .circleci/config.yml
> +      #      - run: apk add --no-cache bash curl git openssh-client
To remove?

2022-05-11 14:56 UTC, cakemanny commented on .circleci/config.yml
> +            #            coverage combine
I assume you're basically having a problem with the `coverage run -m behave ...` run results being overwritten by the `pytest --cov`  run. i.e. they both write to `.coverage`
I think you want to put
```
parallel = True
```
in the `.coveragerc` so that the files get unique names and can be combined

2022-05-11 14:56 UTC, cakemanny commented on reports/TESTS-availability.xml
> +<testsuite name="availability.availability" tests="3" errors="0" failures="0" skipped="0" time="0.55435" timestamp="2022-05-11T14:38:57.645933" hostname="JGRIMER-MBP.lan"><testcase classname="availab
Looks like `reports` is missing from the the `.gitignore`

2022-05-11 14:56 UTC, cakemanny commented on pyticketswitch/event.py
> +            `AvailabilityDetails <pyticketswitch.availability.AvailabilityDetails>`):
I think these also have to be on one line...

![image](https://user-images.githubusercontent.com/4025945/167880545-c69dd2ea-34eb-4377-9943-6f898374cd1b.png)

2022-05-12 11:38 UTC, joegrimeringresso commented on pyticketswitch/event.py
> +            `AvailabilityDetails <pyticketswitch.availability.AvailabilityDetails>`):
I think that's a coincedence. The break is also before the word class in the doc, but after in the code. There's a similar one here:

```
        gross_commission (:class: `Commission <pyticketswitch.commission.Commission>`):
            predicted commission to be shared between ingresso and the partner.
```
which I didn't change, and looks like this in the docs:
![image](https://user-images.githubusercontent.com/88033574/168066382-b4d5bc89-42f5-42c5-9db9-a573179ed824.png)

I will try a test commit now to prove

2022-05-12 11:44 UTC, joegrimeringresso commented on pyticketswitch/event.py
> +            `AvailabilityDetails <pyticketswitch.availability.AvailabilityDetails>`):
yup. same after:
```
        availability_details (:class: `AvailabilityDetails <pyticketswitch.availability.AvailabilityDetails>`):
```
![image](https://user-images.githubusercontent.com/88033574/168067384-d031b7bc-0c07-4454-b406-6866778cfea2.png)

However, it looks uglier in the code, so I might just increase max line length

2022-05-12 13:22 UTC, cakemanny commented on pyticketswitch/event.py
> +            `AvailabilityDetails <pyticketswitch.availability.AvailabilityDetails>`):
```diff
-availability_details (:class: `AvailabilityDetails <pyticketswitch.availability.AvailabilityDetails>`):
+availability_details (:class:`AvailabilityDetails <pyticketswitch.availability.AvailabilityDetails>`):
```
no?

2022-05-12 13:24 UTC, cakemanny commented on pyticketswitch/performance.py
> +        availability_details (:class: `AvailabilityDetails <pyticketswitch.availability.AvailabilityDetails>`):
```suggestion
        availability_details (:class:`AvailabilityDetails <pyticketswitch.availability.AvailabilityDetails>`):
```

2022-05-12 13:44 UTC, cakemanny commented on pyticketswitch/event.py
> +            `AvailabilityDetails <pyticketswitch.availability.AvailabilityDetails>`):
I think that's probably fixed it right?
there's two occurrences though, so you have to find the right one in order to not confused oneself (that's what I did for a while)
i.e. [Event.availability_details](https://pyticketswitch.ingresso.co.uk/api.html?highlight=availabilitydetails#pyticketswitch.event.Event.availability_details) and [Performance.availability_details](https://pyticketswitch.ingresso.co.uk/api.html?highlight=availabilitydetails#pyticketswitch.performance.Performance.availability_details) in the prod docs

2022-05-12 14:02 UTC, joegrimeringresso commented on pyticketswitch/event.py
> +            `AvailabilityDetails <pyticketswitch.availability.AvailabilityDetails>`):
looks the same?? https://deploy-preview-106--pyticketswitch-docs.netlify.app/api This is under Core > Event

![image](https://user-images.githubusercontent.com/88033574/168093291-2bc9b958-6f23-4a82-be89-ffd716ea7007.png)

2022-05-13 08:34 UTC, joegrimeringresso commented
For some reason using parallel didn't really agree with pytest --cov. The reason I used coverage -m pytest, is the former wouldn't output correct coverage. However, when I used `pytest --cov` it didn't use parallel correctly, and overwrote the .coverage.

I found a more clunky solution, but it works:

```
venv/bin/coverage run -m behave --no-capture --no-color --format progress2 --junit --tags=-skip

mv .coverage coverage.b # if I used .coverage.b, pytest still finds and overwrites

pytest --cov tests/*

mv .coverage .coverage.p

mv coverage.b .coverage.b

coverage combine
```

At this point, when I compared the reports, I could see that adding the behave gave a few extra lines of coverage

2022-05-13 08:35 UTC, joegrimeringresso commented on .circleci/config.yml
> +            #            coverage combine
Marking as resolved. See comment down below

2022-05-13 09:15 UTC, joegrimeringresso commented
n.b. We sorted this out. Turns out there was a pytest config thing that was making pytest run --cov anyway

2022-05-16 08:25 UTC, cakemanny commented on pyticketswitch/event.py
> +            `AvailabilityDetails <pyticketswitch.availability.AvailabilityDetails>`):
```suggestion
        availability_details (:class:`AvailabilityDetails <pyticketswitch.availability.AvailabilityDetails>`):
```

2022-05-20 18:29 UTC, cakemanny approved these changes
LGTM! :D

2022-05-23 08:30 UTC, merged