Add tax components
ingresso-group/pyticketswitch pull request #107
Opened 2022-03-17 21:26 UTC by shann9955

2022-03-17 21:29 UTC, shann9955 commented on features/trolley.feature
> +        And I have an existing trolley with items from "7AB" in it
tests were failing locally with `6IF`, but passed when changed to `7AB`

2022-03-17 21:38 UTC, shann9955 commented
I noticed we don't have `sale_combined` or `total_sale_combined` being pulled from the `order` class, would that not replace the `combined_price` and `total_combined_price` functions?... but then I guess we would need to update where those methods are being used externally

2022-03-17 21:51 UTC, shann9955 commented on tests/test_bundle.py
> -        # assert isinstance(bundle.purchase_result, PurchaseResult)
`bundle.purchase_result` doesn't look to be relevant anymore, this failed the tests, I can see its only called only within `is_purchased` function.

2022-03-21 10:54 UTC, cakemanny commented
It would be good if we can get the tests running in CI!
I can see @joegrimeringresso has started on that on #106

2022-03-21 11:19 UTC, joegrimeringresso commented
This is much more comprehensive than what I wrote. Thank you

DO you think it makes sense to add has_tax to the CostRange class?

```
    def has_tax(self):
        return self.total_tax_component is not None
```

Also, I started on a circleci config file - as Dan mentioned - looks like it's not working quite yet, but perhaps you could inlude that? https://github.com/ingresso-group/pyticketswitch/pull/106/files

This is just a comment. WIll read code more now...

2022-03-21 15:11 UTC, joegrimeringresso approved these changes

2022-03-22 10:15 UTC, cakemanny requested changes
Heya, it looks like you've updated Send Methods but not the tests, so I think that might have been a miss :) 

I've added a few comments too. But this is looking pretty good so far 👍 

Also, I see this is your first contribution to pyticketswitch! See #108 for all the places that you'll need to update the version when it comes to it 😄 

/cc @charklewis

2022-03-22 10:15 UTC, cakemanny commented on pyticketswitch/send_method.py
> +            kwargs.update(send_cost_tax_component=send_cost_tax_component)
Hey @shann9955 , could you add a comment to this to explain why permitted countries affects the tax component.
I assume it has something to do with per-country tax law?
Though I also feel like this should be made as a core decision... 😕

2022-03-23 15:34 UTC, shann9955 commented on pyticketswitch/bundle.py
> +                 debitor=None, terms_and_conditions=None, purchase_result=None, send_cost_tax_component=None, total_combined_tax_component=None, total_surcharge_tax_sub_component=None):
Fixed this, but I'm seeing quite a few files that hasn't been checked with max line of 80 characters, I'll apply the linter to the other files in a separate branch.

2022-03-23 15:35 UTC, shann9955 commented on pyticketswitch/cost_range.py
> +
is this what you meant @joegrimeringresso ?

2022-03-23 15:45 UTC, joegrimeringresso commented on pyticketswitch/cost_range.py
> +
yeah. that's a better idea!

2022-03-24 16:51 UTC, cakemanny commented on pyticketswitch/bundle.py
> +                 debitor=None, terms_and_conditions=None, purchase_result=None, send_cost_tax_component=None, total_combined_tax_component=None, total_surcharge_tax_sub_component=None):
> Fixed this, but I'm seeing quite a few files that hasn't been checked with max line of 80 characters, I'll apply the linter to the other files in a separate branch.

ahh, ok, so maybe 90 as the actual limit could be better I wonder ... @shann9955 

I ran the linter since you updated the config and feel fixing for 80 is going to cause way too much unneeded churn 😬 

There might some cases where using the `# noqa ` would make sense... but I'm not sure is possible due to the line being exceeded in the docstrings.
_started writing this ages ago_

2022-03-24 17:00 UTC, merged